name: Bun CI

on:
  push:
    branches: [main]
  pull_request:

env:
  VITE_API_URL: 'http://localhost:8000'
  VITE_SESSION_KEY: 'newsletter_api_key'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Prepare svelte-kit
        run: bun prepare
      - name: Install playwright browser
        run: npx playwright install firefox
      - name: Execute unit tests
        run: bun test:unit
      - name: Execute browser tests
        run: bun test:e2e
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Prepare svelte-kit
        run: bun prepare
      - name: Run linter
        run: bun prettier --check .
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Prepare svelte-kit
        run: bun prepare
      - name: Run svelte-check
        run: bun check
